#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <stdlib.h>
#include "util.h"

// function that is responsible to execute the Leaf_Counter executable in the right path (subdirectory). Use piping to get information about the file generated by the Leaf_Counter executable. This file path is then used to accumulate votes.
void execVote_Counter(char **argv) {
  pid_t childPid = fork();
  if (childPid == 0) {
    char *args[4];
		args[0] = "./votecounter";
		args[1] = argv[1];
		args[2] = argv[2];
    args[3] = argv[3];
		execvp(args[0], args);
		perror("Error encountered while executing the process : ");
  } else {
    wait(NULL);
  }
}

int main(int argc, char **argv){
  // check whether the number of arguments is correct.
	if (argc != 5){
		printf("Usage: %s %s %s %s %s\n", argv[0], "input.txt", "relative path (form - /home/dir1/dir2)", "relative path (form - /home/dir1/dir2)", "number of times to run");
		return -1;
	}
  int lim = atoi(argv[4]);
  for (int i = 0; i < lim; i++) {
    printf("Iteration Number:%d\n", i+1);
    execVote_Counter(argv);
  }
  return 1;
}